# .github/workflows/jekyll-docker.yml
# Este workflow é para publicar um site HTML estático no GitHub Pages.
# Apesar do nome do arquivo, ele NÃO usa Jekyll ou Docker, pois não é necessário
# para um simples arquivo HTML. Ele usa as actions padrão do GitHub Pages.

name: Deploy Static HTML to GitHub Pages

on:
  # Aciona o workflow em pushes para a branch especificada
  push:
    branches:
      - main # Altere para a sua branch principal se for diferente (ex: master)

  # Permite que você execute este workflow manualmente a partir da aba Actions
  workflow_dispatch:

# Define permissões para o GITHUB_TOKEN para permitir o deploy no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy concorrente, cancelando execuções anteriores na mesma branch/PR
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # URL da página publicada
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Ação para clonar seu repositório

      - name: Setup Pages
        uses: actions/configure-pages@v5 # Ação oficial para configurar o GitHub Pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Ação para empacotar seu site
        with:
          # Upload do diretório raiz do seu repositório.
          # Se o seu Waifu_generator_pony_diffusion.html (ou index.html) estiver na raiz,
          # este path é o correto.
          # Se estiver em uma subpasta (ex: 'public' ou 'dist'), altere o path aqui.
          # Exemplo: path: './public'
          path: '.' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Ação oficial para fazer o deploy no GitHub Pages
